### PR TITLE
Scraper for social media posts

### PR DESCRIPTION
**Pull request by j-h-s**

### CODE REVIEW

**Comment by Putr** [comment]
Great work, but there are a few must-fix bugs that need to be addressed before merge:

- Scraped FB images are extremely small (within a 130x130 box)
- It scrapes all pages of results every single time. This means we get lots of extra requests (which are a problem - we don't want to get banned). Your --data option was a good thing to implement, but take it one step further and detect if you already have history older than what you're getting and stop at that point (as most of the time you'll only need to scrape 1-3 new posts)

Sorry for taking so long to review this :(

**Comment by j-h-s** [comment]
That shouldn't be happening at all.

1) getImageSource (FacebookService.php, line ~250) finds the version closest to 480x480 of each image (except cover images). It should only save the 130x130 thumbnail as a backup if something fails, and the scraper should tell you when that happens.

2) We count every post every time, because fb doesn't have a simple postCount we can get, but that's only a very small request each time. When getting details, getTimeLimit (ScraperServices.php, line ~175) checks the db and tells the scraper to only go back as far as the latest entry (within a page of results, in case any recent posts were updated since the last scrape), unless the user has added the --full option.

I just tested these points on my end, and they're both working as I described.

**Comment by Putr** [comment]
1. This may have something to do with different API version as I debugged the api output and the 130 thumb was the only thing in the returned dataset. I'll generate a new APP with new keys and test again.

2. I just realized that I did not test this fully as I never allowed the command to compleate so the posts were never imported into the db, just scraped. Will do again.

**Comment by j-h-s** [comment]
Yeah, maybe. My code assumes you're using fb api graph v2.7 (see 1st commit in this branch). They changed a lot of the field names between 2.5 and 2.7, so if you're trying to access the new fields on the old graph it will fail and give you the thumbnail as a backup.

**Pull request merged**
